#!/bin/sh /etc/rc.common

# cake-qos-simple

# author: Lynx of OpenWrt

# This simple shell script:
# 1) sets up an intermediate functional block for use with wan ingress (ifb-wan); and
# 2) mirrors packets from wan ingress to ifb-wan having restored DSCPs from the conntracks
# 3) sets up cake on wan egress (for upload) and on ifb-wan (for download)

# This facilitates the optional use of the diffserv functionality in cake for improving qos when
# bandwidth is contrained is contrained by leveraging the connection trability in Linux. 

# To make use of this optional diffserv functionality, DSCPs must be: 
# a) written to packets on upload by LAN clients or route; and
# b) written to conntracks on upload for restoration on download

# Proper operation can be evaluated using 'tcpdump -i ifb-wan -v' to inspect TOS values and by using
# 'tc -s qdisc show dev wan' and 'tc -s qdisc show dev ifb-wan' to inspect the tinning in cake

# cake-qos-simple configuration options:

ul_if=wan # upload interface (ifb for download derived from this)

cake_ul_rate_Mbps=10 # cake upload rate in Mbit/s
cake_dl_rate_Mbps=10 # cake download rate in Mbit/s

cake_ul_options="diffserv4 dual-srchost nonat wash no-ack-filter noatm overhead 0"
cake_dl_options="diffserv4 dual-dsthost nonat nowash ingress no-ack-filter noatm overhead 0"

# end of cake-qos-simple configuration options

dl_if=ifb-${ul_if}

START=91
STOP=4

EXTRA_COMMANDS="upload download"
EXTRA_HELP="	
	cake-qos-simple custom commands:

	upload		show stats for upload interface
	download	show stats for download interface"

start() 
{
	ip link add name ${dl_if} type ifb
	ip link set ${dl_if} up

	tc qdisc add dev ${ul_if} handle ffff: ingress
	
	# For each upload interface ingress packet conditionally restore DSCP from conntrack if available
	tc filter add dev ${ul_if} parent ffff: protocol ip matchall action ctinfo dscp 63 128 action mirred egress redirect dev $dl_if

	# These lines set up the cake instances and must be modified for desired operation including cake bandwidths
	tc qdisc add dev ${ul_if} root cake bandwidth ${cake_ul_rate_Mbps}Mbit ${cake_ul_options}
	tc qdisc add dev ${dl_if} root cake bandwidth ${cake_dl_rate_Mbps}Mbit ${cake_dl_options}
}

stop() 
{
	tc qdisc del dev ${ul_if} ingress
	tc qdisc del dev ${ul_if} root
        tc qdisc del dev ${dl_if} root
        ip link set ${dl_if} down
        ip link del ${dl_if}
} 

upload() 
{
	tc -s qdisc show dev $ul_if
}

download()
{
	tc -s qdisc show dev $dl_if
}
